### ISSUE TITLE
Taller Flutter

### ISSUE THREAD

**Issue by kiritodemonslayer** [ISCOUTB/DG-DEPE#1]
vamos a hacer el tutorial de Flutter https://youtu.be/wTibz0TuW7k?si=gN6hVdt1I03vgVcT

**Comment by Pars2906** [comment]
Hice la instalación de flutter en visual studio code y toque algunas cosas del codigo

![Image](https://github.com/user-attachments/assets/4c6bde86-c358-4d51-81c4-98c9f8439b71)

**Comment by kiritodemonslayer** [comment]
instalación de fluttter tuve algunos problemas con unos paquetes de c++ para visual, también me adelante un pco y ya instale Android estudio
![Image](https://github.com/user-attachments/assets/31f89763-0f70-40d7-b6db-abb4f80960ce)
[](url)
