### ISSUE TITLE
mejorar diseño de entorno

### ISSUE THREAD

**Issue by kiritodemonslayer** [ISCOUTB/DG-DEPE#14]

**Comment by Pars2906** [comment]
[Update.main](https://github.com/ISCOUTB/DG-DEPE/commit/6203cda8b1d2168c66e41e559efc8b85ef206e56)
[Update Login](https://github.com/ISCOUTB/DG-DEPE/commit/b03bc0a915907eae633a520ecc7a9a01becb216a)
[Update Dashboard](https://github.com/ISCOUTB/DG-DEPE/commit/636c862f50983c759d94708bf830ca96c7de740c)
