### ISSUE TITLE
Definir Wireframes

### ISSUE THREAD

**Issue by kiritodemonslayer** [ISCOUTB/DG-DEPE#3]

**Comment by Pars2906** [comment]
Encontré esta pagina donde podemos trabajar: https://miro.com/es/

![Image](https://github.com/user-attachments/assets/22b582af-dbb4-49e3-9547-086c23f7723d)

**Comment by FrederG** [comment]
Nuesta idea es hacer un Wireframe algo parecido a esto
### Dashboard
![Image](https://github.com/user-attachments/assets/85e7f3c1-1910-4780-b1c4-18b65a204a1d) 
### Login
![Image](https://github.com/user-attachments/assets/9ecbe4db-8ef4-43bf-8f0a-4975fdc5916d) 
### Paleta de colore
![Image](https://github.com/user-attachments/assets/bb23fe51-b4c0-4f23-b833-8b751a8b0807)

**Comment by jairoserrano** [comment]
faltan los wirframes especificos de la app.

**Comment by FrederG** [comment]
Actualizacion de Dashboard con wirframes especificos
![dash](https://github.com/user-attachments/assets/268db581-6f48-4d3b-848f-ed3c08b487e7)
