### ISSUE TITLE
Crear la interfaz web

### ISSUE THREAD

**Issue by Pars2906** [ISCOUTB/DG-DEPE#4]

**Comment by FrederG** [comment]
Intente replicar el login que habia mostrado anteriormente con ayuda de I.A, ![Image](https://github.com/user-attachments/assets/e33bc442-fb16-4e08-aa4b-52bc8d9f0661)
lo que llevo es esto

**Comment by Pars2906** [comment]
Hice el diseño de la pagina al momento de ingresar
![image](https://github.com/user-attachments/assets/dd041232-1f64-47e0-aa82-75856ac89196)

**Comment by Pars2906** [comment]
Diseño de inicio de sesión
![image](https://github.com/user-attachments/assets/44ef4bf4-fb3a-4874-bd18-252485cd10c3)

**Comment by jairoserrano** [comment]
adelante
