### ISSUE TITLE
Login

### ISSUE THREAD

**Issue by FrederG** [ISCOUTB/DG-DEPE#5]
- Desarrollar el sistema de registro que valide y acepte solo correos institucionales de la UTB.
Implementar la funcionalidad para el envío de correos de confirmación.
Configurar el sistema para rechazar correos no institucionales y mostrar un mensaje de error adecuado.
Realizar pruebas de seguridad para asegurar la protección de los datos de los usuarios durante el registro.

**Comment by Pars2906** [comment]
[Login_update](https://github.com/ISCOUTB/DG-DEPE/commit/4663a0870604aed21ce8f13280d496e0e7adcc46)
